[phases.setup]
aptPkgs = [
  "libcairo2",
  "libpango-1.0-0",
  "libpangocairo-1.0-0",
  "libgdk-pixbuf2.0-0",
  "libglib2.0-0",
  "libgobject-2.0-0",
  "libffi-dev",
  "shared-mime-info",
  "build-essential"
]

[phases.install]
commands = [
  "apt-get update && apt-get install -y libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf-2.0-0 libglib2.0-0 libgirepository-1.0-1 gobject-introspection libffi-dev shared-mime-info build-essential",
  "python -m pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
