# nixpacks.toml — configuração estável e compatível com Railway

[phases.setup]
# Instala pacotes necessários via Nix (sem apt-get)
nixPkgs = [
  "python311Full",
  "cairo",
  "pango",
  "gdk-pixbuf",
  "glib",
  "libffi",
  "gobject-introspection",
  "shared-mime-info"
]

[phases.install]
# Instala as dependências do projeto com o pip embutido do Python
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
# Comando de inicialização do Streamlit
cmd = "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
