# nixpacks.toml — versão corrigida e funcional no Railway

[phases.setup]
# Pacotes que o Nix deve instalar
nixPkgs = [
  "python311",
  "cairo",
  "pango",
  "gdk-pixbuf",
  "glib",
  "libffi",
  "gobject-introspection",
  "shared-mime-info"
]

[phases.install]
# Instalar dependências Python via pip
cmds = ["python -m ensurepip && pip install --no-cache-dir -r requirements.txt"]

[start]
# Comando de inicialização do Streamlit
cmd = "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
