[phases.setup]
nixPkgs = ["python311", "pip", "cairo", "pango", "gdk-pixbuf", "glib", "libffi", "gobject-introspection", "shared-mime-info"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
