[phases.setup]
aptPkgs = [
  "libcairo2",
  "libpango-1.0-0",
  "libpangocairo-1.0-0",
  "libpangoft2-1.0-0",
  "libgdk-pixbuf-2.0-0",
  "libglib2.0-0",
  "libharfbuzz0b",
  "libffi-dev",
  "libxml2",
  "libxslt1.1",
  "libfreetype6",
  "libfontconfig1",
  "libfribidi0",
  "libjpeg62-turbo",
  "zlib1g",
  "pkg-config",
  "shared-mime-info",
  "fonts-liberation",
  "build-essential",
  "gtk3",                # ✅ adiciona todo o runtime GTK, incluindo libgobject
  "libgirepository-1.0-1",
  "gobject-introspection",
  "libgirepository1.0-dev"
]
