[phases.setup]
aptPkgs = [
  "libcairo2",
  "libpango-1.0-0",
  "libpangocairo-1.0-0",
  "libgdk-pixbuf2.0-0",
  "libffi-dev",
  "shared-mime-info",
  "build-essential"
]

[phases.install]
commands = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
