# nixpacks.toml — configuração estável para Railway + Streamlit + WeasyPrint

[phases.setup]
nixPkgs = [
  "python311Full",
  "cairo",
  "pango",
  "gdk-pixbuf",
  "glib",
  "libffi",
  "gobject-introspection",
  "shared-mime-info"
]

[phases.install]
# Usamos o Python diretamente para chamar o pip embutido
cmds = ["python3 -m pip install --no-cache-dir -r requirements.txt"]

[start]
# Executa o Streamlit
cmd = "python3 -m streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
